// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(NotALotteryGameAPIDbContext))]
    partial class NotALotteryGameAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.OneHourLottery", b =>
                {
                    //b.Property<Guid>("Id")
                    //    .ValueGeneratedOnAdd()
                    //    .HasColumnType("uniqueidentifier");

                    b.Property<long>("Id")
                        .IsRequired()
                        .HasColumnType("bigint");  

                    b.Property<string>("AddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OneHourLottery");
                });

            modelBuilder.Entity("webapi.Models.TwoHourLottery", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressId")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("TwoHourLottery");
            });

            modelBuilder.Entity("webapi.Models.SixHourLottery", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressId")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("SixHourLottery");
            });

            modelBuilder.Entity("webapi.Models.TwelveHourLottery", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressId")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("TwelveHourLottery");
            });

            modelBuilder.Entity("webapi.Models.DailyLottery", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressId")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("DailyLottery");
            });

            modelBuilder.Entity("webapi.Models.WeeklyHourLottery", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressId")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("WeeklyHourLottery");
            });

            modelBuilder.Entity("webapi.Models.LottoTimes", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("DateAndTime")
                    .IsRequired()
                    .HasColumnType("datetime");

                b.HasKey("Id");

                b.ToTable("LottoTimes");
            });

            modelBuilder.Entity("webapi.Models.Winners", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AddressId")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("AmountPulse")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<int>("LottoType")
                    .IsRequired()
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Winners");
            });

#pragma warning restore 612, 618
        }
    }
}
